paths: {}
responses:
    Response:
        description: A Response is an response that is used to send data.
        headers:
            data:
                description: |-
                    The error message
                    in: string
            message:
                description: |-
                    The error message
                    in: string
                type: string
            status:
                description: |-
                    Status code of the response
                    in: string
                format: int64
                type: integer
        schema: {}
swagger: "2.0"
